// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {udpdiscovery} from '../models';

export function DiscoverDevices():Promise<Array<udpdiscovery.Device>>;

export function OpenInBrowser(arg1:string):Promise<void>;
