// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscoverDevices() {
  return window['go']['udpdiscovery']['App']['DiscoverDevices']();
}

export function OpenInBrowser(arg1) {
  return window['go']['udpdiscovery']['App']['OpenInBrowser'](arg1);
}
